### ISSUE TITLE
keepalived segfault using track_process in vrrp_instance

### ISSUE THREAD

**Issue by jontow** [acassen/keepalived#1150]
Built and reproduced on release-tagged 2.0.13 and from git cloned this afternoon on CentOS 7.6.1810/x86_64 in a VM.  Segfault consistently shows the same line in handle_proc_ev().  I've compiled with LOG_ALL_PROCESS_EVENTS defined, but it doesn't seem to get to any logging before segfaulting.  Is there any additional info I can obtain to help troubleshoot this?

Linux lb-1.vlab.example.com 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Configuration file looks like this:
```
global_defs {
  notification_email_from lb@example.com
  smtp_server localhost
  smtp_connect_timeout 30
  script_user root
  enable_script_security
}

vrrp_track_process check_haproxy {
  process    "haproxy"
  weight    10
  quorum    1
  delay     2000
}

vrrp_instance tl_lb_eth1 {
  interface                 eth1
  state                     BACKUP
  virtual_router_id         108
  priority                  100
  advert_int                1
  garp_master_delay         5

  authentication {
    auth_type PASS
    auth_pass LB_108
  }

  track_process {
    check_haproxy
  }

  virtual_ipaddress {
    10.11.2.210/24 dev eth1
    10.11.2.211/24 dev eth1
  }
}
```

```
[jtowne@lb-1.vlab GIT-keepalived]$ sudo ./keepalived/keepalived -lnmR
Fri Mar  8 17:09:59 2019: Starting Keepalived v2.0.13 (02/24,2019), git commit v2.0.13-10-gf903f07+
Fri Mar  8 17:09:59 2019: Running on Linux 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 (built for Linux 3.10.0)
Fri Mar  8 17:09:59 2019: Opening file '/etc/keepalived/keepalived.conf'.
Fri Mar  8 17:09:59 2019: Remove a zombie pid file /var/run/keepalived.pid
Fri Mar  8 17:09:59 2019: Registering Kernel netlink reflector
Fri Mar  8 17:09:59 2019: Registering Kernel netlink command channel
Fri Mar  8 17:09:59 2019: Opening file '/etc/keepalived/keepalived.conf'.
Fri Mar  8 17:09:59 2019: (tl_lb_eth1) Changing effective priority from 100 to 110
Fri Mar  8 17:09:59 2019: Registering gratuitous ARP shared channel
Fri Mar  8 17:09:59 2019: (tl_lb_eth1) Entering BACKUP STATE (init)
Segmentation fault
```

gdb backtrace follows:
```
[jtowne@lb-1.vlab GIT-keepalived]$ sudo gdb ./keepalived/keepalived core.19460 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-114.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/jtowne/GIT-keepalived/keepalived/keepalived...done.
[New LWP 19460]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./keepalived/keepalived -lnmR'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000564ca4ce39e0 in handle_proc_ev (nl_sock=4) at track_process.c:603
603                                 cpu_seq[proc_ev->cpu] != -1 &&
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7_6.3.x86_64 iptables-1.4.21-28.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-37.el7_6.x86_64 libcom_err-1.42.9-13.el7.x86_64 libnl3-3.2.28-4.el7.x86_64 libselinux-2.5-14.1.el7.x86_64 openssl-libs-1.0.2k-16.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) info threads
  Id   Target Id         Frame 
* 1    Thread 0x7f0e6c0be840 (LWP 19460) 0x0000564ca4ce39e0 in handle_proc_ev (nl_sock=4) at track_process.c:603
(gdb) bt full
#0  0x0000564ca4ce39e0 in handle_proc_ev (nl_sock=4) at track_process.c:603
        nlmsghdr = 0x7fff07aa8920
        len = 76
        buf = "L\000\000\000\003", '\000' <repeats 11 times>, "\001\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000(\000\000\000\000\000\000\000\377\377\377\377\230\250\257\215;\025", '\000' <repeats 78 times>, "\240\002\032\000p\000\002\000l\000\001", '\000' <repeats 13 times>, "\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001", '\000' <repeats 47 times>...
        cn_msg = 0x7fff07aa8930
        addr = {nl_family = 16, nl_pad = 0, nl_pid = 0, nl_groups = 1}
        addrlen = 12
#1  0x0000564ca4ce3e11 in read_process_update (thread=0x564ca540e7e0) at track_process.c:721
        rc = 0
#2  0x0000564ca4d1c8fb in thread_call (thread=0x564ca540e7e0) at scheduler.c:1745
No locals.
#3  process_threads (m=0x564ca540a180) at scheduler.c:1793
        thread = 0x564ca540e7e0
        thread_type = <optimized out>
#4  0x0000564ca4d1cdb1 in launch_thread_scheduler (m=<optimized out>) at scheduler.c:1890
No locals.
#5  0x0000564ca4cda805 in keepalived_main (argc=<optimized out>, argv=<optimized out>) at main.c:1953
        report_stopped = true
        uname_buf = {sysname = "Linux", '\000' <repeats 59 times>, nodename = "lb-1.vlab.example.com", '\000' <repeats 48 times>, 
          release = "3.10.0-862.14.4.el7.x86_64", '\000' <repeats 38 times>, version = "#1 SMP Wed Sep 26 15:12:11 UTC 2018", '\000' <repeats 29 times>, 
          machine = "x86_64", '\000' <repeats 58 times>, domainname = "(none)", '\000' <repeats 58 times>}
        end = 0x7fff07aa9b05 ".vlab.example.com"
        exit_code = 0
#6  0x00007f0e6a7ec3d5 in __libc_start_main () from /lib64/libc.so.6
No symbol table info available.
#7  0x0000564ca4cd912e in _start ()
No symbol table info available.
```

**Comment by pqarmitage** [comment]
Many thanks for the detailed issue report.

Commit 729befd resolves the segfault. It appears that a 3.10 kernel sends some messages that aren't sent on later kernels, and the code wasn't handling the additional messages properly.

**Comment by szahri** [comment]
Hi there,
I have the same issue on Redhat Linux Server 7.8 (Maipo) with 3.10.0-1127-19.1.el7.x86_64 kernel.
I used the exact same config above just to ensure I received the same error and I did.

Log below :
`2020-06-23T11:01:09.072862+00:00 testserver Keepalived[60605]: Starting VRRP child process, pid=60668
2020-06-23T11:01:09.073183+00:00 testserver Keepalived_vrrp[60668]: Registering Kernel netlink reflector
2020-06-23T11:01:09.073438+00:00 testserver Keepalived_vrrp[60668]: Registering Kernel netlink command channel
2020-06-23T11:01:09.074092+00:00 testserver Keepalived_vrrp[60668]: Opening file '/etc/keepalived/keepalived.conf'.
2020-06-23T11:01:09.074393+00:00 testserver Keepalived_vrrp[60668]: (Line 31) (VI_1) track process check_haproxy not found, ignoring...
2020-06-23T11:01:09.074699+00:00 testserver Keepalived_vrrp[60668]: Assigned address 10.10.20.206 for interface eth0
2020-06-23T11:01:09.074995+00:00 testserver Keepalived_vrrp[60668]: Assigned address fe80::21d:d8ff:feb7:1f49 for interface eth0
2020-06-23T11:01:09.076648+00:00 testserver kernel: keepalived[60668]: segfault at ffffffffffffffe8 ip 000056003819f4c9 sp 00007ffe7f20d550 error 5 in keepalived[560038162000+7f000]
2020-06-23T11:01:09.076975+00:00 testserver Keepalived[60605]: pid 60668 exited due to segmentation fault (SIGSEGV).
2020-06-23T11:01:09.077239+00:00 testserver Keepalived[60605]:  Please report a bug at https://github.com/acassen/keepalived/issues
2020-06-23T11:01:09.077476+00:00 testserver Keepalived[60605]:  and include this log from when keepalived started, a description
2020-06-23T11:01:09.077826+00:00 testserver Keepalived[60605]:  of what happened before the crash, your configuration file and the details below.
2020-06-23T11:01:09.078111+00:00 testserver Keepalived[60605]:  Also provide the output of keepalived -v, what Linux distro and version
2020-06-23T11:01:09.078348+00:00 testserver Keepalived[60605]:  you are running on, and whether keepalived is being run in a container or VM.
2020-06-23T11:01:09.078625+00:00 testserver Keepalived[60605]:  A failure to provide all this information may mean the crash cannot be investigated.
2020-06-23T11:01:09.078859+00:00 testserver Keepalived[60605]:  If you are able to provide a stack backtrace with gdb that would really help.
2020-06-23T11:01:09.079085+00:00 testserver Keepalived[60605]:  Source version 2.1.2
2020-06-23T11:01:09.079313+00:00 testserver Keepalived[60605]:  Built with kernel headers for Linux 3.10.0
2020-06-23T11:01:09.079537+00:00 testserver Keepalived[60605]:  Running on Linux 3.10.0-1127.el7.x86_64 #1 SMP Tue Feb 18 16:39:12 EST 2020
2020-06-23T11:01:09.079780+00:00 testserver Keepalived[60605]:  Command line: '/usr/sbin/keepalived' '-D'
2020-06-23T11:01:09.080006+00:00 testserver Keepalived[60605]:  configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix=
2020-06-23T11:01:09.080229+00:00 testserver Keepalived[60605]:                     --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin`

I'm using the latest stable code 2.1.2.
