### ISSUE TITLE
VRRP sync group name may be corrupted and can lead to a crash

### ISSUE THREAD

**Issue by araujorm** [acassen/keepalived#1599]
**Describe the bug**
The VRRP group name can get corrupted and lead to a crash, if the config file has some quirks.

**To Reproduce**
Use the following config file to start keepalived:
```
global_defs {
    router_id BADGNAME
    enable_snmp_vrrp
}

vrrp_sync_group group1 {
    group {
        vrrp1
    }
}

vrrp_instance vrrp1 {
    state BACKUP
    interface enp1s0  # <-- CHANGE HERE TO MEET YOUR FIRST INTERFACE
    virtual_router_id 20
    advert_int 1
    authentication {
        auth_type AH
        auth_pass somthing
   }

   virtual_ipaddress {
       172.28.29.254/24 dev enp1s0 label enp1s0:254
   }
}
```
Note that this only seems to happen when the config file has as a group with only 1 instance, which rightfully so produces a warning when starting keepalived, followed by a message that's probably related:
```
Mon Jun  1 19:01:12 2020: Sync group group1 has only 1 virtual router(s) - this probably isn't what you want
Mon Jun  1 19:01:12 2020: sync group group1 - iname vector exists when freeing group
```
Later on, notice that something's not right:
```
Mon Jun  1 19:01:16 2020: VRRP_Group((null)) Syncing instances to MASTER state
```
In this state, there is at least one way to make keepalived crash, probably others, but triggering a snmp walk on .1.3.6.1.4.1.9586 does that, triggering a segfault. Didn't test with notify scripts but most likely strange things will happen too.

**Expected behavior**
Group name should not be corrupted and keepalived should not segfault.

Or keepalived should just not allow a vrrp group with a single vrrp instance and bail out? I'm not the one to decide that, although perhaps throwing a faltal error earlier might make sense. 

When deciding, recall that currently you can specify a second entry on the group even if that one doesn't exist (e.g. place vrrp2 inside the `group {}` but don't create any vrrp instance called vrrp2), which also produces a warning. When testing the fix, I would advise testing with that scenario too (currently it also garbles the group name).

**Keepalived version**
Tested with commit ace4fbdb355a657238c6a4af11f629dc030c805f (latest master at the time of writing this).
```
Keepalived v2.0.20 (unknown)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.18.0
Running on Linux 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-snmp --enable-snmp-rfc --enable-sha1 --with-init=systemd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld

Config options:  LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA IPTABLES NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK
```

**Distro (please complete the following information):**
 - Name: CentOS
 - Version: 8
 - Architecture: x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
N/A

**Configuration file:**
See above.

**Notify and track scripts**
Not used but may make the crash more frequent.

**System Log entries**
See above for relevant entries.

**Did keepalived coredump?**
Yes, and although it was in SNMP code in this case, I don't think the fault lies there specifically but somewhere earlier in the config file parsing and data structure initialization as described above. Anyway, `coredump gdb` output follows:
```
Core was generated by `keepalived -D -n -l'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fd92191acd5 in __strlen_avx2 () from /lib64/libc.so.6

(gdb) bt
#0  0x00007fd92191acd5 in __strlen_avx2 () from /lib64/libc.so.6
#1  0x0000560bd1b66120 in vrrp_snmp_instance (vp=0x7fffd589e0e0, name=0x7fffd589dce0, length=0x7fffd589d8d8, exact=0, var_len=0x7fffd589d8d0, write_method=<optimized out>)
    at vrrp_snmp.c:2135
#2  0x00007fd92214a800 in netsnmp_old_api_helper () from /lib64/libnetsnmpagent.so.35
#3  0x00007fd92215a017 in netsnmp_call_handlers () from /lib64/libnetsnmpagent.so.35
#4  0x00007fd92216b182 in handle_var_requests () from /lib64/libnetsnmpagent.so.35
#5  0x00007fd92216b89f in handle_getnext_loop () from /lib64/libnetsnmpagent.so.35
#6  0x00007fd92216c522 in netsnmp_handle_request () from /lib64/libnetsnmpagent.so.35
#7  0x00007fd92216cb1a in handle_snmp_packet () from /lib64/libnetsnmpagent.so.35
#8  0x00007fd921dd4762 in _sess_process_packet () from /lib64/libnetsnmp.so.35
#9  0x00007fd921dd57f6 in _sess_read () from /lib64/libnetsnmp.so.35
#10 0x00007fd921dd632d in snmp_sess_read2 () from /lib64/libnetsnmp.so.35
#11 0x00007fd921dd637b in snmp_read2 () from /lib64/libnetsnmp.so.35
#12 0x00007fd921dd63d6 in snmp_read () from /lib64/libnetsnmp.so.35
#13 0x0000560bd1b74e36 in snmp_read_thread (thread=0x560bd30f9bd0) at scheduler.c:1515
#14 0x0000560bd1b750de in thread_call (thread=0x560bd30f9bd0) at scheduler.c:1923
#15 process_threads (m=0x560bd3076870) at scheduler.c:1923
#16 0x0000560bd1b75845 in launch_thread_scheduler (m=<optimized out>) at scheduler.c:2030
#17 0x0000560bd1b3f091 in start_vrrp_child () at vrrp_daemon.c:1130
#18 start_vrrp_child () at vrrp_daemon.c:1000
#19 0x0000560bd1b15bd2 in start_keepalived (thread=<optimized out>) at main.c:530
#20 0x0000560bd1b750de in thread_call (thread=0x560bd30767f0) at scheduler.c:1923
#21 process_threads (m=0x560bd3076230) at scheduler.c:1923
#22 0x0000560bd1b75845 in launch_thread_scheduler (m=<optimized out>) at scheduler.c:2030
#23 0x0000560bd1b17f8f in keepalived_main (argc=4, argv=<optimized out>) at main.c:2392
#24 0x00007fd9217e0873 in __libc_start_main () from /lib64/libc.so.6
#25 0x0000560bd1b15a8e in _start ()
```

**Additional context**
N/A

**Comment by pqarmitage** [comment]
Commit 1ae858f resolves this issue. Many thanks for reporting it.
