### ISSUE TITLE
keepalived segfaults with unicast_peer

### ISSUE THREAD

**Issue by brown-midas** [acassen/keepalived#1908]
**Describe the bug**
keepalived segfaults if I configure a vrrp_instance that uses unicast

**To Reproduce**
enable a vrrp_instance that contains unicast_peer entries

**Expected behavior**
keepalived should run without segfaults. If there's an error in the configuration, keepalived should report it without crashing

**Keepalived version**
```
Keepalived v2.1.5 (07/13,2020)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.8.0
Running on Linux 5.11.21-200.fc33.x86_64 #1 SMP Sat May 15 20:31:00 UTC 2021

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-snmp --enable-snmp-rfc --enable-nftables --disable-iptables --disable-ipset --enable-sha1 --with-init=systemd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CC=gcc CFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection LDFLAGS=-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld

Config options:  NFTABLES LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK
```

**Distro (please complete the following information):**
 - Name: Fedora
 - Version: 33
 - Architecture: x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
VMware ESX 7.0

**Configuration file:**
```
vrrp_script chk_httpd_service {
    script "/usr/bin/killall -0 httpd"
    interval 2                      # check every 2 seconds
    weight 2                        # add 2 points of prio if OK
}

vrrp_script chk_backend_service {
    script "/usr/bin/killall -0 backend"
    interval 2                      # check every 2 seconds
    weight 10                       # add 10 points of prio if OK
}

# frontend
vrrp_instance VI_0 {
    interface ens160
    state MASTER
    virtual_router_id 203
    priority 100                    # 101 on master, 100 on backup
    advert_int 5                    # advertise instance every 5s
    garp_master_delay 10            # delay for gratuitous ARP after transition to MASTER
    garp_lower_prio_delay 10        # send gratuitous ARP if a lower priority advert is seen
    garp_lower_prio_repeat 1        # send gratuitous ARP if a lower priority advert is seen
    garp_master_refresh 60          # repeat gratuitous ARP every 60s when MASTER
    garp_master_refresh_repeat 2    # send 2 gratuitous ARPs when repeating

    authentication {
        auth_type PASS
        auth_pass frontend
    }
    virtual_ipaddress {
        10.0.0.54 dev ens160 label ens160:0
    }
    track_script {
        chk_httpd_service
    }
}

vrrp_instance VI_1 {
    state BACKUP
    interface ens160
#    unicast_src_ip 10.0.0.55
    unicast_peer {
        10.0.0.55 # node1
        10.0.0.56 # node2
    }
    virtual_router_id 211
    priority 101                    # 101 on master, 100 on backup
    advert_int 5                    # advertise instance every 5s
    garp_master_delay 10            # delay for gratuitous ARP after transition to MASTER
    garp_lower_prio_delay 10        # send gratuitous ARP if a lower priority advert is seen
    garp_lower_prio_repeat 1        # send gratuitous ARP if a lower priority advert is seen
    garp_master_refresh 60          # repeat gratuitous ARP every 60s when MASTER
    garp_master_refresh_repeat 2    # send 2 gratuitous ARPs when repeating

    authentication {
        auth_type PASS              # PASS or AH, PASS is recommended
        auth_pass backend1          # max 8 chars
    }
    virtual_ipaddress {
        10.0.0.33 dev ens160 label ens160:1
    }
    track_script {
        chk_backend_service
    }
}

vrrp_instance VI_2 {
    state BACKUP
    interface ens160
#    unicast_src_ip 10.0.0.55
    unicast_peer {
        10.0.0.55 # node1
        10.0.0.56 # node2
    }
    virtual_router_id 212
    priority 100                    # 101 on master, 100 on backup
    advert_int 5                    # advertise instance every 5s
    garp_master_delay 10            # delay for gratuitous ARP after transition to MASTER
    garp_lower_prio_delay 10        # send gratuitous ARP if a lower priority advert is seen
    garp_lower_prio_repeat 1        # send gratuitous ARP if a lower priority advert is seen
    garp_master_refresh 60          # repeat gratuitous ARP every 60s when MASTER
    garp_master_refresh_repeat 2    # send 2 gratuitous ARPs when repeating

    authentication {
        auth_type PASS              # PASS or AH, PASS is recommended
        auth_pass backend2          # max 8 chars
    }
    virtual_ipaddress {
        10.0.0.34 dev ens160 label ens160:2
    }
    track_script {
        chk_backend_service
    }
}
```

**Notify and track scripts**
 No external scripts in use

**System Log entries**
```
May 21 08:53:20 node1 Keepalived[2053]: Starting Keepalived v2.1.5 (07/13,2020)
May 21 08:53:20 node1 Keepalived[2053]: Running on Linux 5.11.21-200.fc33.x86_64 #1 SMP Sat May 15 20:31:00 UTC 2021 (built for Linux 5.8.0)
May 21 08:53:20 node1 Keepalived[2053]: Command line: '/usr/sbin/keepalived' '-P' '-D'
May 21 08:53:20 node1 Keepalived[2053]: Opening file '/etc/keepalived/keepalived.conf'.
May 21 08:53:20 node1 Keepalived[2054]: NOTICE: setting config option max_auto_priority should result in better keepalived performance
May 21 08:53:20 node1 Keepalived[2054]: Starting VRRP child process, pid=2055
May 21 08:53:20 node1 Keepalived_vrrp[2055]: Registering Kernel netlink reflector
May 21 08:53:20 node1 Keepalived_vrrp[2055]: Registering Kernel netlink command channel
May 21 08:53:20 node1 Keepalived_vrrp[2055]: Opening file '/etc/keepalived/keepalived.conf'.
May 21 08:53:20 node1 Keepalived_vrrp[2055]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
May 21 08:53:20 node1 Keepalived_vrrp[2055]: (/etc/keepalived/keepalived.conf: Line 29) Truncating auth_pass to 8 characters
May 21 08:53:20 node1 Keepalived_vrrp[2055]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
May 21 08:53:20 node1 Keepalived_vrrp[2055]: Assigned address 10.0.0.55 for interface ens160
May 21 08:53:20 node1 Keepalived_vrrp[2055]: Assigned address fe80::250:56ff:fea6:7f97 for interface ens160
May 21 08:53:20 node1 Keepalived_vrrp[2055]: Registering gratuitous ARP shared channel
May 21 08:53:20 node1 Keepalived_vrrp[2055]: (VI_0) removing VIPs.
May 21 08:53:20 node1 Keepalived_vrrp[2055]: (VI_1) removing VIPs.
May 21 08:53:20 node1 Keepalived[2054]: pid 2055 exited due to segmentation fault (SIGSEGV).
May 21 08:53:20 node1 Keepalived[2054]:   Please report a bug at https://github.com/acassen/keepalived/issues
May 21 08:53:20 node1 Keepalived[2054]:   and include this log from when keepalived started, a description
May 21 08:53:20 node1 Keepalived[2054]:   of what happened before the crash, your configuration file and the details below.
May 21 08:53:20 node1 Keepalived[2054]:   Also provide the output of keepalived -v, what Linux distro and version
May 21 08:53:20 node1 Keepalived[2054]:   you are running on, and whether keepalived is being run in a container or VM.
May 21 08:53:20 node1 Keepalived[2054]:   A failure to provide all this information may mean the crash cannot be investigated.
May 21 08:53:20 node1 Keepalived[2054]:   If you are able to provide a stack backtrace with gdb that would really help.
May 21 08:53:20 node1 Keepalived[2054]:   Source version 2.1.5
May 21 08:53:20 node1 Keepalived[2054]:   Built with kernel headers for Linux 5.8.0
May 21 08:53:20 node1 Keepalived[2054]:   Running on Linux 5.11.21-200.fc33.x86_64 #1 SMP Sat May 15 20:31:00 UTC 2021
May 21 08:53:20 node1 Keepalived[2054]:   Command line: '/usr/sbin/keepalived' '-P' '-D'
May 21 08:53:20 node1 Keepalived[2054]:   configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix=
May 21 08:53:20 node1 Keepalived[2054]:                      --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin
May 21 08:53:20 node1 Keepalived[2054]:                      --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share
May 21 08:53:20 node1 Keepalived[2054]:                      --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec
May 21 08:53:20 node1 Keepalived[2054]:                      --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man
May 21 08:53:20 node1 Keepalived[2054]:                      --infodir=/usr/share/info --enable-snmp --enable-snmp-rfc --enable-nftables
May 21 08:53:20 node1 Keepalived[2054]:                      --disable-iptables --disable-ipset --enable-sha1 --with-init=systemd
May 21 08:53:20 node1 Keepalived[2054]:                      build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu
May 21 08:53:20 node1 Keepalived[2054]:                      PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CC=gcc CFLAGS=-O2
May 21 08:53:20 node1 Keepalived[2054]:                      -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall
May 21 08:53:20 node1 Keepalived[2054]:                      -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS
May 21 08:53:20 node1 Keepalived[2054]:                      -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong
May 21 08:53:20 node1 Keepalived[2054]:                      -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic
May 21 08:53:20 node1 Keepalived[2054]:                      -fasynchronous-unwind-tables -fstack-clash-protection LDFLAGS=-Wl,-z,relro
May 21 08:53:20 node1 Keepalived[2054]:                      -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
May 21 08:53:20 node1 Keepalived[2054]:   Config options: NFTABLES LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP
May 21 08:53:20 node1 Keepalived[2054]:                   SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3
May 21 08:53:20 node1 Keepalived[2054]:   System options: PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API
May 21 08:53:20 node1 Keepalived[2054]:                   LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN
May 21 08:53:20 node1 Keepalived[2054]:                   FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS
May 21 08:53:20 node1 Keepalived[2054]:                   FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL
May 21 08:53:20 node1 Keepalived[2054]:                   FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS
May 21 08:53:20 node1 Keepalived[2054]:                   IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION
May 21 08:53:20 node1 Keepalived[2054]:                   LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY
May 21 08:53:20 node1 Keepalived[2054]:                   IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE
May 21 08:53:20 node1 Keepalived[2054]:                   VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH
May 21 08:53:20 node1 Keepalived[2054]:                   GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK
May 21 08:53:20 node1 Keepalived[2054]: VRRP child process(2055) died: Respawning
May 21 08:53:20 node1 Keepalived[2054]: Restart of VRRP process delayed 0 seconds to limit respawn rate
May 21 08:53:20 node1 Keepalived[2054]: Starting VRRP child process, pid=2062
May 21 08:53:20 node1 Keepalived_vrrp[2062]: Registering Kernel netlink reflector
May 21 08:53:20 node1 Keepalived_vrrp[2062]: Registering Kernel netlink command channel
May 21 08:53:20 node1 Keepalived_vrrp[2062]: Opening file '/etc/keepalived/keepalived.conf'.
May 21 08:53:20 node1 Keepalived_vrrp[2062]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
May 21 08:53:20 node1 Keepalived_vrrp[2062]: (/etc/keepalived/keepalived.conf: Line 29) Truncating auth_pass to 8 characters
May 21 08:53:20 node1 Keepalived_vrrp[2062]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
May 21 08:53:20 node1 Keepalived_vrrp[2062]: Assigned address 10.0.0.55 for interface ens160
May 21 08:53:20 node1 Keepalived_vrrp[2062]: Assigned address fe80::250:56ff:fea6:7f97 for interface ens160
May 21 08:53:20 node1 Keepalived_vrrp[2062]: Registering gratuitous ARP shared channel
May 21 08:53:20 node1 Keepalived_vrrp[2062]: (VI_0) removing VIPs.
May 21 08:53:20 node1 Keepalived_vrrp[2062]: (VI_1) removing VIPs.
May 21 08:53:20 node1 Keepalived[2054]: pid 2062 exited due to segmentation fault (SIGSEGV).
May 21 08:53:20 node1 Keepalived[2054]:   Please report a bug at https://github.com/acassen/keepalived/issues
```

**Did keepalived coredump?**
```
Reading symbols from /usr/sbin/keepalived...
Reading symbols from /usr/lib/debug/usr/sbin/keepalived-2.1.5-3.fc33.x86_64.debug...
[New LWP 458891]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/sbin/keepalived -P -D'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  inet_sockaddrcmp (a=0x0, b=0x561266d712c8) at utils.c:767
767	utils.c: No such file or directory.
Missing separate debuginfos, use: dnf debuginfo-install audit-libs-3.0.1-2.fc33.x86_64 bzip2-libs-1.0.8-4.fc33.x86_64 glibc-2.32-4.fc33.x86_64 libacl-2.2.53-9.fc33.x86_64 libattr-2.4.48-10.fc33.x86_64 libcap-2.48-2.fc33.x86_64 libdb-5.3.28-45.fc33.x86_64 libgcc-10.3.1-1.fc33.x86_64 libmnl-1.0.4-12.fc33.x86_64 libnftnl-1.1.7-3.fc33.x86_64 libnl3-3.5.0-5.fc33.x86_64 libxcrypt-4.4.20-2.fc33.x86_64 libzstd-1.5.0-1.fc33.x86_64 lm_sensors-libs-3.6.0-5.fc33.x86_64 lua-libs-5.4.2-1.fc33.x86_64 net-snmp-agent-libs-5.9-4.fc33.x86_64 net-snmp-libs-5.9-4.fc33.x86_64 openssl-libs-1.1.1k-1.fc33.x86_64 perl-libs-5.32.1-469.fc33.x86_64 popt-1.18-2.fc33.x86_64 rpm-libs-4.16.1.3-1.fc33.x86_64 sqlite-libs-3.34.1-1.fc33.x86_64 systemd-libs-246.13-1.fc33.x86_64 xz-libs-5.2.5-4.fc33.x86_64 zlib-1.2.11-23.fc33.x86_64
(gdb) bt
#0  inet_sockaddrcmp (a=0x0, b=0x561266d712c8) at utils.c:767
#1  0x0000561265fb91e1 in already_exist_sock (unicast_src=0x561266d712c8, ifp=0x561266d6bbb0, proto=<optimized out>,
    family=2, l=0x561266d6b490) at vrrp_scheduler.c:410
#2  vrrp_create_sockpool (l=0x561266d6b490) at vrrp_scheduler.c:471
#3  vrrp_dispatcher_init (thread=<optimized out>) at vrrp_scheduler.c:533
#4  0x0000561265fdbbd6 in thread_call (thread=0x561266d6b4f0) at scheduler.c:1876
#5  process_threads (m=0x561266d6ae00) at scheduler.c:1940
#6  0x0000561265fe80da in launch_thread_scheduler (m=0x561266d6ae00) at scheduler.c:2047
#7  start_vrrp_child.isra.0 () at vrrp_daemon.c:1044
#8  0x0000561265fdbbd6 in thread_call (thread=0x561266d63e60) at scheduler.c:1876
#9  process_threads (m=0x561266d637e0) at scheduler.c:1940
#10 0x0000561265f7f843 in launch_thread_scheduler (m=0x561266d637e0) at scheduler.c:2047
#11 keepalived_main (argc=<optimized out>, argv=<optimized out>) at main.c:2384
#12 0x00007f4e130e31e2 in __libc_start_main () from /lib64/libc.so.6
#13 0x0000561265f774fe in _start ()
```

**Additional context**
This started after upgrading this VM from Fedora 32 (running keepalived 2.0.20) to Fedora 33 (running keepalived 2.1.5).
Changing from using unicast to multicast avoids the segfaults and appears to work OK.
Other VMs running Fedora 33 and keepalived 2.1.5 seem OK with unicast_peer, so I guess I'm not seeing a contributing factor.
The previous working config (on F33 and keepalived 2.0.20) did not specify unicast_src_ip (I'm not sure if it's required or not), but including it does not seem to solve the problem.

**Comment by pqarmitage** [comment]
@brown-midas Many thanks for reporting this and for providing the stack backtrace which made it easy to identify the source of the problem.

Commit 25684fd resolves the segfault.
