### ISSUE TITLE
KEEPALIVED-MIB vrrpInstanceIndex Index is forcibly 0, breaks pysnmp

### ISSUE THREAD

**Issue by commonism** [acassen/keepalived#1988]
**Describe the bug**
The KEEPALIVED-MIB does not work with pysnmp due to improper indexing for the vrrpInstanceIndex

https://github.com/acassen/keepalived/blob/994d90ff916a01cdd583e107cfef0281d7d117ce/doc/KEEPALIVED-MIB.txt#L926-L929

The vrrpInstanceIndex basically forbids tio have values != 0, which does not work for a table index.

It raises …

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyasn1/type/constraint.py", line 32, in __call__
    self._testValue(value, idx)
  File "/usr/lib/python3/dist-packages/pyasn1/type/constraint.py", line 748, in _testValue
    raise error.ValueConstraintError(
pyasn1.type.error.ValueConstraintError: all of (<SingleValueConstraint object, consts 0>,) failed for "1"
```

**To Reproduce**
```
from pysnmp import hlapi
from pysnmp.smi import builder, view, error
def main():

    oids = ["KEEPALIVED-MIB", "vrrpInstanceName"]

    # MIB View Controller implements various queries to loaded MIBs
    mibView = view.MibViewController(mibBuilder = builder.MibBuilder())

    r = hlapi.ObjectIdentity(*oids).resolveWithMib(mibView)
    print(r)

    oids.append(1)

    r = hlapi.ObjectIdentity(*oids).resolveWithMib(mibView)
    print(r)


if __name__ == '__main__':
    main()
```

**Expected behavior**
Proper resolve of the oid.

**Keepalived version**
```
Keepalived v2.1.5 (07/13,2020)
```

**Distro (please complete the following information):**
 - Name: Debian
 - Version: Bullseye
 - Architecture: x86_64

**Additional context**
Source: pysmi
Version: 0.3.2-2

Source: python-pysnmp4
Version: 4.4.12-1

**Comment by pqarmitage** [comment]
[RFC 2578 - Structure of Management Information Version 2](https://datatracker.ietf.org/doc/html/rfc2578#section-7.1.1) states at section 7.1.1:
```
The INTEGER type (but not the Integer32 type) may also be used to
   represent integer-valued information as named-number enumerations.
   In this case, only those named-numbers so enumerated may be present
   as a value.
```
This leaves no doubt that the KEEPALIVED MIB is incorrect.

The question now arises about what impact it will have changing the MIB to:
```
 vrrpInstanceIndex OBJECT-TYPE 
     SYNTAX Integer32 (0..2147483647)
```
since the incorrect form has been used since SNMP support was added to keepalived in commit 66daab3 (in 2012).

If using snmpwalk, as an example
```
KEEPALIVED-MIB::vrrpAddressAdvertising.static.1 = INTEGER: notAdvertised(2)
KEEPALIVED-MIB::vrrpAddressAdvertising.static.2 = INTEGER: notAdvertised(2)
KEEPALIVED-MIB::vrrpAddressAdvertising.1.1 = INTEGER: advertised(1)
KEEPALIVED-MIB::vrrpAddressAdvertising.2.1 = INTEGER: notAdvertised(2)
KEEPALIVED-MIB::vrrpAddressAdvertising.3.1 = INTEGER: notAdvertised(2)
KEEPALIVED-MIB::vrrpAddressAdvertising.3.2 = INTEGER: notAdvertised(2)
KEEPALIVED-MIB::vrrpRouteAddressType.static.1 = INTEGER: ipv4(1)
KEEPALIVED-MIB::vrrpRouteAddressType.static.2 = INTEGER: ipv4(1)
KEEPALIVED-MIB::vrrpRouteAddressType.static.3 = INTEGER: ipv6(2)
KEEPALIVED-MIB::vrrpRouteDestination.static.1 = Hex-STRING: C0 A8 64 00 
KEEPALIVED-MIB::vrrpRouteDestination.static.2 = Hex-STRING: C0 A8 C8 00 
KEEPALIVED-MIB::vrrpRouteDestination.static.3 = Hex-STRING: 20 01 04 70 69 E9 00 01 00 02 00 00 00 00 00 04 
KEEPALIVED-MIB::vrrpRouteDestinationMask.static.1 = Gauge32: 24
KEEPALIVED-MIB::vrrpRouteDestinationMask.static.2 = Gauge32: 24
KEEPALIVED-MIB::vrrpRouteDestinationMask.static.3 = Gauge32: 128
KEEPALIVED-MIB::vrrpRouteMetric.static.1 = Gauge32: 0
KEEPALIVED-MIB::vrrpRouteMetric.static.2 = Gauge32: 12
KEEPALIVED-MIB::vrrpRouteMetric.static.3 = Gauge32: 12
KEEPALIVED-MIB::vrrpRouteScope.static.1 = INTEGER: global(14)
KEEPALIVED-MIB::vrrpRouteScope.static.2 = INTEGER: linkLocal(2)
KEEPALIVED-MIB::vrrpRouteScope.static.3 = INTEGER: linkLocal(2)
KEEPALIVED-MIB::vrrpRouteType.static.1 = INTEGER: ecmp(2)
KEEPALIVED-MIB::vrrpRouteType.static.2 = INTEGER: unicast(1)
KEEPALIVED-MIB::vrrpRouteType.static.3 = INTEGER: unicast(1)
```
will change to
```
KEEPALIVED-MIB::vrrpAddressAdvertising.0.1 = INTEGER: notAdvertised(2)
KEEPALIVED-MIB::vrrpAddressAdvertising.0.2 = INTEGER: notAdvertised(2)
KEEPALIVED-MIB::vrrpAddressAdvertising.1.1 = INTEGER: advertised(1)
KEEPALIVED-MIB::vrrpAddressAdvertising.2.1 = INTEGER: notAdvertised(2)
KEEPALIVED-MIB::vrrpAddressAdvertising.3.1 = INTEGER: notAdvertised(2)
KEEPALIVED-MIB::vrrpAddressAdvertising.3.2 = INTEGER: notAdvertised(2)
KEEPALIVED-MIB::vrrpRouteAddressType.0.1 = INTEGER: ipv4(1)
KEEPALIVED-MIB::vrrpRouteAddressType.0.2 = INTEGER: ipv4(1)
KEEPALIVED-MIB::vrrpRouteAddressType.0.3 = INTEGER: ipv6(2)
KEEPALIVED-MIB::vrrpRouteDestination.0.1 = Hex-STRING: C0 A8 64 00 
KEEPALIVED-MIB::vrrpRouteDestination.0.2 = Hex-STRING: C0 A8 C8 00 
KEEPALIVED-MIB::vrrpRouteDestination.0.3 = Hex-STRING: 20 01 04 70 69 E9 00 01 00 02 00 00 00 00 00 04 
KEEPALIVED-MIB::vrrpRouteDestinationMask.0.1 = Gauge32: 24
KEEPALIVED-MIB::vrrpRouteDestinationMask.0.2 = Gauge32: 24
KEEPALIVED-MIB::vrrpRouteDestinationMask.0.3 = Gauge32: 128
KEEPALIVED-MIB::vrrpRouteMetric.0.1 = Gauge32: 0
KEEPALIVED-MIB::vrrpRouteMetric.0.2 = Gauge32: 12
KEEPALIVED-MIB::vrrpRouteMetric.0.3 = Gauge32: 12
KEEPALIVED-MIB::vrrpRouteScope.0.1 = INTEGER: global(14)
KEEPALIVED-MIB::vrrpRouteScope.0.2 = INTEGER: linkLocal(2)
KEEPALIVED-MIB::vrrpRouteScope.0.3 = INTEGER: linkLocal(2)
KEEPALIVED-MIB::vrrpRouteType.0.1 = INTEGER: ecmp(2)
KEEPALIVED-MIB::vrrpRouteType.0.2 = INTEGER: unicast(1)
KEEPALIVED-MIB::vrrpRouteType.0.3 = INTEGER: unicast(1)
```

Will the replacement of `.static.` with `.0.` have an adverse affect on anyone? It doesn't change any OIDs; so far as I can see the only affect is a change in textual representation.

If anyone can identify any problems with making the above change to the MIB, please add a comment below; otherwise I think it is right to change the MIB.

**Comment by vincentbernat** [comment]
I agree with the analysis. When I wrote the MIB, I was under the impression that non-defined values would be valid as all clients at the time didn't have a grip about that. Browsing many MIBs, I don't see examples where we can a few enumerated values and accept a range.

Removing `static` may break clients requesting the OID by its name. But it seems quite minor compared to the alternative (duplicate the OID and deprecate the old one).

**Comment by pqarmitage** [comment]
@commonism Many thanks for reporting this. Commit 70d389a resolves this issue.
