### ISSUE TITLE
parse error in config file -> many core dumps

### ISSUE THREAD

**Issue by Grummel7** [acassen/keepalived#2104]
**Describe the bug**
**To Reproduce**
**System Log entries**
I've made a small mistake in the config file: I forgot the last closing brace.
When I started the daemon, it did report a parse error...
```
Keepalived[2766755]: Opening file '/etc/keepalived/keepalived.conf'.
Keepalived[2766755]: There are 1 missing '}'s or extra '{'s
```
...but started the vrrp process, which dumped a core...
```
Starting VRRP child process, pid=2766757
pid 2766757 exited due to segmentation fault (SIGSEGV)
...
VRRP child process(2766757) died: Respawning'
```
...was respawn, dumped again, etc.

**Expected behavior**
I guess the daemon should simply exit if there is a parse error in the config file.
It definitely should not create dozens of core dumps

**Keepalived version**
```
keepalived -v
Keepalived v2.1.5 (07/13,2020)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.18.0
Running on Linux 4.18.0-348.12.2.el8_5.x86_64 #1 SMP Mon Jan 17 07:06:06 EST 2022

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-libiptc --disable-ipset --enable-snmp --enable-snmp-rfc --enable-sha1 --with-init=systemd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld

Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK

```

**Distro (please complete the following information):**
 - Name: Red Hat Enterprise Linux release 8.5 (Ootpa)
 
**Configuration file:**
```
vrrp_instance soap_1 {
        state BACKUP
        interface ens192
        virtual_router_id 51
        priority 254
        advert_int 1
        authentication {
              auth_type PASS
              auth_pass 12345
        }
        virtual_ipaddress {
              192.168.71.103/24
        }
```

**Did keepalived coredump?**
```
#0  0x00007f9039c82e4f in fgets () from /lib64/libc.so.6
#1  0x000055be8f12cbc4 in read_line.constprop ()
#2  0x000055be8f12e306 in process_stream ()
#3  0x000055be8f12eec9 in init_data ()
#4  0x000055be8f0f5fef in start_vrrp ()
#5  0x000055be8f0f68e4 in start_vrrp_child ()
#6  0x000055be8f129b5e in process_threads ()
#7  0x000055be8f0cfa4f in keepalived_main ()
#8  0x00007f9039c35493 in __libc_start_main () from /lib64/libc.so.6
#9  0x000055be8f0cd55e in _start ()
```

**Comment by pqarmitage** [comment]
Many thanks for reporting this issue. This was resolved by commit 9ee6902 which was first included in keepalived v2.2.0.

Issue #2067 reported a similar (but different) problem. I will submit a patch to resolve that issue soon, but it is over 6500 lines long.
