### ISSUE TITLE
VRRP segfaults if ip6_tables module is not loaded

### ISSUE THREAD

**Issue by vvidic** [acassen/keepalived#457]
The following sample configuration with version 1.2.24 generates a segfault:
```
global_defs {
    vrrp_version 3 # for ipv6
    vrrp_iptables  # do not touch iptables
    router_id SID2
}

vrrp_instance VIP {
    state BACKUP
    priority 100
    virtual_router_id 29
    interface ens3
    virtual_ipaddress {
        192.168.122.111
    }
}

vrrp_instance VIP6 {
    state BACKUP
    priority 100
    virtual_router_id 29
    interface ens3
    virtual_ipaddress {
        fe80::111
    }
}
```

This is the syslog contents:
```
Nov 19 19:14:21 sid2 Keepalived[32409]: Starting VRRP child process, pid=32675
Nov 19 19:14:21 sid2 Keepalived_vrrp[32675]: Netlink reflector reports IP 192.168.122.29 added
Nov 19 19:14:21 sid2 Keepalived_vrrp[32675]: Netlink reflector reports IP fe80::5054:ff:fe02:50d3 added
Nov 19 19:14:21 sid2 Keepalived_vrrp[32675]: Registering Kernel netlink reflector
Nov 19 19:14:21 sid2 Keepalived_vrrp[32675]: Registering Kernel netlink command channel
Nov 19 19:14:21 sid2 Keepalived_vrrp[32675]: Registering gratuitous ARP shared channel
Nov 19 19:14:21 sid2 Keepalived_vrrp[32675]: Unable to load ipset library
Nov 19 19:14:21 sid2 Keepalived_vrrp[32675]: Unable to initialise ipsets
Nov 19 19:14:21 sid2 Keepalived_vrrp[32675]: Opening file '/etc/keepalived/keepalived.conf'.
Nov 19 19:14:21 sid2 Keepalived_vrrp[32675]: VRRP_Instance(VIP) removing protocol VIPs.
Nov 19 19:14:21 sid2 Keepalived_vrrp[32675]: VRRP_Instance(VIP) removing protocol iptable drop rule
Nov 19 19:14:21 sid2 Keepalived_vrrp[32675]: VRRP_Instance(VIP6) removing protocol VIPs.
Nov 19 19:14:21 sid2 Keepalived_vrrp[32675]: VRRP_Instance(VIP6) removing protocol iptable drop rule
Nov 19 19:14:21 sid2 Keepalived[32409]: pid 32675 exited due to segmentation fault (SIGSEGV).
Nov 19 19:14:21 sid2 Keepalived[32409]:   Please report a bug at https://github.com/acassen/keepalived/issues
Nov 19 19:14:21 sid2 Keepalived[32409]:   and include this log from when keepalived started, what happened
Nov 19 19:14:21 sid2 Keepalived[32409]:   immediately before the crash, and your configuration file.
```

Stacktrace ends in libip6tc version 1.6.0+snapshot20161117-1 from Debian sid:

```
#0  0x00007f38ce93e35e in ?? () from /usr/lib/x86_64-linux-gnu/libip6tc.so.0
#1  0x00007f38ce940577 in ?? () from /usr/lib/x86_64-linux-gnu/libip6tc.so.0
#2  0x0000557ca67c4a79 in ip6tables_process_entry ()
#3  0x0000557ca67c39b4 in ?? ()
#4  0x0000557ca67c3c98 in handle_iptable_rule_to_vip ()
#5  0x0000557ca67bb4f2 in handle_iptable_rule_to_iplist ()
#6  0x0000557ca67b0c84 in ?? ()
#7  0x0000557ca67b2015 in vrrp_restore_interface ()
#8  0x0000557ca67b4223 in vrrp_complete_init ()
#9  0x0000557ca67ab64d in ?? ()
#10 0x0000557ca67abac5 in start_vrrp_child ()
#11 0x0000557ca67abbf8 in ?? ()
#12 0x0000557ca67d0905 in launch_scheduler ()
#13 0x0000557ca679a1d5 in keepalived_main ()
#14 0x00007f38cd4932b1 in __libc_start_main ()
   from /lib/x86_64-linux-gnu/libc.so.6
#15 0x0000557ca6798f5a in _start ()
```

Calling ``modprobe ip6_tables`` stops the segfaults immediately but maybe there is a better fix?

**Comment by pqarmitage** [comment]
Many thanks for the details report, diagnosis and stack trace. That all made it quite simple to resolve.

Commit d52fa00 resolves the issue.
