### ISSUE TITLE
Keepalived-vip pod crashes in kubernetes deployment

### ISSUE THREAD

**Issue by ajmulhollan1** [acassen/keepalived#641]
Hello,

I've got keepalived-vip setup as a kubernetes deployment, alongside my Nginx ingress controller.

I'm trying to figure out why I had the following error for about 15 minutes.

```
F0822 07:13:14.932629       1 keepalived.go:122] keepalived error: signal: hangup
goroutine 1 [running]:
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.stacks(0x1d9fd00, 0xc400000000, 0x52, 0x9b)
    /usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:766 +0xa5
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).output(0x1d7f800, 0xc400000003, 0xc420318000, 0x1d19fea, 0xd, 0x7a, 0x0)
    /usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:717 +0x337
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).printf(0x1d7f800, 0x3, 0x14ff53a, 0x14, 0xc42071fd10, 0x1, 0x1)
    /usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:655 +0x14c
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.Fatalf(0x14ff53a, 0x14, 0xc42071fd10, 0x1, 0x1)
    /usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.(*keepalived).Start(0xc4200df540)
    /usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/keepalived.go:122 +0x249
main.main()
    /usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/main.go:124 +0x402
```

I also couldn't ping the VIP, I just got `Destination Host Unreachable` after a lot of researching I couldn't find an answer, and I'd like to know how to fix this if it happens again?

It just started working again after a while, it was around 15-30 minutes.

Any help appreciated.

**Comment by ajmulhollan1** [comment]
Apologies I think I've posted this in the wrong repo
