### ISSUE TITLE
keepalived 1.4.0 segmentation fault in vs_end_handler 

### ISSUE THREAD

**Issue by rik78** [acassen/keepalived#751]
Keepalived crashes with the example configuration included.

```c
static void
vs_end_handler(void)
{
    virtual_server_t *vs = LIST_TAIL_DATA(check_data->vs);
    real_server_t *rs;
    element e;

    /* If the real (sorry) server uses tunnel forwarding, the address family
     * does not have to match the address family of the virtaul server */
    if (vs->s_svr->forwarding_method != IP_VS_CONN_F_TUNNEL) {
        if (vs->af == AF_UNSPEC)
            vs->af = vs->s_svr->addr.ss_family;
        else if (vs->af != vs->s_svr->addr.ss_family) {
            log_message(LOG_INFO, "Address family of virtual server and sorry server %s don't match - skipping sorry server.", inet_sockaddrtos(&vs->s_svr->addr));
            FREE(vs->s_svr);
            vs->s_svr = NULL;
        }
    }
```

```shell
(gdb) bt
#0  0x00005555555620de in vs_end_handler () at check_parser.c:123
#1  0x000055555558b43e in process_stream (keywords_vec=0x5555557ab380, need_bob=<optimized out>) at parser.c:391
#2  0x000055555558b6a9 in read_conf_file (conf_file=conf_file@entry=0x55555558e1d8 "/etc/keepalived/keepalived.conf") at parser.c:479
#3  0x000055555558be4a in init_data (conf_file=0x55555558e1d8 "/etc/keepalived/keepalived.conf", init_keywords=0x555555562bd0 <check_init_keywords>)
    at parser.c:1084
#4  0x000055555555eda0 in start_check (old_checkers_queue=old_checkers_queue@entry=0x0) at check_daemon.c:138
#5  0x000055555555f22d in start_check_child () at check_daemon.c:392
#6  0x000055555555a8c7 in start_keepalived () at main.c:302
#7  keepalived_main (argc=2, argv=<optimized out>) at main.c:1063
#8  0x00007ffff6f3fc05 in __libc_start_main () from /lib64/libc.so.6
#9  0x0000555555558fc1 in _start ()
(gdb) p vs->s_svr
$1 = (real_server_t *) 0x0
(gdb)
```

**Comment by pqarmitage** [comment]
@rik78 Am I missing something, or is the example configuration not included?

Just so that I can make sure I am looking at exactly the right lines in the code, could you also state what git commit you are using.

P.S. Travis-CI builds are now enabled - many thanks.

**Comment by pqarmitage** [comment]
I've found a cause of a segfault if a virtual server doesn't have a sorry server configured. Commit 4955985 resolves that segfault.

Could you please confirm it it resolves your problem, and if so close the issue.

**Comment by rik78** [comment]
I tested with 1.4.0 tarball. I will recheck with your fix, thanks!

**Comment by hydrapolic** [comment]
Thanks for the fix @pqarmitage, hit the same problem:
https://bugs.gentoo.org/643992

**Comment by rik78** [comment]
It works now! Thanks for the fix @pqarmitage

**Comment by hydrapolic** [comment]
Since this is even present in the example configuration, please consider releasing 1.4.1. Thank you.
