### ISSUE TITLE
Keepalived is coredumped when logfile cannot be opened.

### ISSUE THREAD

**Issue by ilyaevseev** [acassen/keepalived#980]
Just run under non-privileged user:

    $ : > /tmp/keepalived.conf

    $ ./keepalived-2.0.6/keepalived/keepalived -D -l -t -f /tmp/keepalived.conf
    Segmentation fault (core dumped)

    $ coredumpctl gdb
    ..
    (gdb) bt
    #0  __GI___fileno (fp=0x0) at fileno.c:35
    #1  0x0000555a84063ce3 in open_log_file (name=0x555a840649c9 "/tmp/keepalived.config-check", prog=prog@entry=0x0, namespace=namespace@entry=0x0,         instance=instance@entry=0x0) at logger.c:111
    #2  0x0000555a84026021 in parse_cmdline (argv=0x7ffe78eeeac8, argc=6) at main.c:1107
    #3  keepalived_main (argc=6, argv=0x7ffe78eeeac8) at main.c:1314
    #4  0x00007f853f57a24b in __libc_start_main (main=0x555a84024ea0 <main>, argc=6, argv=0x7ffe78eeeac8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe78eeeab8) at ../csu/libc-start.c:308
    #5  0x0000555a84024eda in _start ()

**Comment by ilyaevseev** [comment]
See my pull request #981 please.
